export const services = [
  { name: "Emergency Dentistry", icon: "/Images/icons/emergency-vehicle.png", link: "/services/emergency-dentistry" },
  { name: "Root Canal", icon: "/Images/icons/dental-drill.png", link: "/services/root-canal" },
  { name: "Oral Surgery", icon: "/Images/icons/oral surgery (2).png", link: "/services/oral-surgery" },
  { name: "Cosmetic Dentistry", icon: "/Images/icons/Cosmetic dentistry.png", link: "/services/cosmetic-dentistry" },
  { name: "Dental Fillings", icon: "/Images/icons/dental-drill (1).png", link: "/services/dental-fillings" },
  { name: "Dental Implants", icon: "/Images/icons/tooth-implant.png", link: "/services/dental-implants" },
  { name: "Orthodontics", icon: "/Images/icons/orthodontics.png", link: "/services/orthodontics" },
  { name: "Crowns and Bridges", icon: "/Images/icons/teeth-crown.png", link: "/services/crowns-and-bridges" },
  { name: "Dental Emergencies", icon: "/Images/icons/female-dentist.png", link: "/services/dental-emergencies" },
  { name: "Tooth Extraction", icon: "/Images/icons/dental-drill.png", link: "/services/tooth-extraction" },
  { name: "Whitening & Veneers", icon: "/Images/icons/teeth-whitening.png", link: "/services/whitening-&-veneers" },
  { name: "Invisalign", icon: "/Images/icons/dentures.png", link: "/services/invisalign" },
  { name: "Kids & Children Dentistry", icon: "/Images/icons/braces (1).png", link: "/services/kids-&-children-dentistry" },
  { name: "Permanent Teeth Replacement", icon: "/Images/icons/change-teeth.png", link: "/services/permanent-teeth-replacement" },
  { name: "Sports Dentistry", icon: "/Images/icons/dental-chair.png", link: "/services/sports-dentistry" },
  { name: "Wisdom Teeth", icon: "/Images/icons/injection.png", link: "/services/wisdom-teeth" },
  { name: "Endodontics", icon: "/Images/icons/orthodontics.png", link: "/services/endodontics" },
  { name: "Same-Day-Dentistry", icon: "/Images/icons/dental-care.png", link: "/services/same-day-dentistry" },
  { name: "Painless Treatment", icon: "/Images/icons/medicine.png", link: "/services/painless-treatment" },
  { name: "Perio Protect", icon: "/Images/icons/teeth-protection.png", link: "/services/perio-protect" },
  { name: "Halitosis", icon: "/Images/icons/teeth-whitening.png", link: "/services/halitosis" },
]; 